---
version: 1
disable_existing_loggers: True

formatters:
  simple:
    class: logging.Formatter
    format: "%(module)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  info_file:
    class: logging.handlers.RotatingFileHandler
    level: NOTSET
    formatter: simple
    filename: logs/info.log
    encoding: utf8
    backupCount: 10

root:
  level: INFO, NOTSET
  handlers: [info_file]